version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"  # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
    environment:
      MYSQL_DATABASE: dmafrica
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: DMAfrica2024!
      MYSQL_ROOT_PASSWORD: DMAfrica2024!

volumes:
  db_data:  # Define a volume for MySQL data persistence
